version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: userapi-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: user-api
      POSTGRES_PASSWORD: 123456
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: